### ISSUE TITLE
Crash on Upgrading-Workbench (With Optifine?)

### ISSUE THREAD

**Issue by lightlike** [MachineMuse/MachineMusePowersuits#867]
Minecraft: 1.12.2
Forge: 14.23.5.2770
MMP-Version: 0.5.0.14

Possible Cause:
- Optifine? (v: HD U E2)
- No items set for Upgrade?

Recreation:
- Hover over Last Energy-Upgrade

> java.lang.StringIndexOutOfBoundsException: String index out of range: -1
> 	at java.lang.String.substring(String.java:1955)
> 	at net.machinemuse.powersuits.utils.MuseStringUtils.wrapStringToLength(MuseStringUtils.java:203)
> 	at net.machinemuse.powersuits.common.gui.tinker.clickable.ClickableModule.getToolTip(ClickableModule.java:39)
> 	at net.machinemuse.powersuits.common.gui.tinker.frame.ModuleSelectionFrame.getToolTip(ModuleSelectionFrame.java:186)
> 	at net.machinemuse.powersuits.common.gui.MuseGui.getToolTip(MuseGui.java:282)
> 	at net.machinemuse.powersuits.common.gui.MuseGui.drawToolTip(MuseGui.java:242)
> 	at net.machinemuse.powersuits.common.gui.MuseGui.func_73863_a(MuseGui.java:106)
> 	at net.machinemuse.powersuits.common.gui.tinker.GuiTinkerTable.func_73863_a(GuiTinkerTable.java:98)
> 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
> 	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.optifine.reflect.Reflector.callVoid(Reflector.java:654)
> 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by lehjr** [comment]
Hopefully fixed in Alpha 15 which should be visible in a few minutes.

**Comment by lightlike** [comment]
Nope. Still crashing. Could this be a problem with localization?

**Comment by lehjr** [comment]
might be. What language are you using?

**Comment by lightlike** [comment]
German.

**Comment by lehjr** [comment]
I'll have to see if I can replicate the issue and go from there. It's related to the localization, and I need to add better error handling for it.

**Comment by lehjr** [comment]
I managed to replicate the issue replacing the English translations with the German ones. I have a tested working version that I'm uploading shortly . That said, many of the translations were done using Google translator, so they might be absolute nonsense.

**Comment by lightlike** [comment]
Works fine now. Sorry I couldn't check this any faster.
