### ISSUE TITLE
[1.12.2] Phantom Fall Damage

### ISSUE THREAD

**Issue by Xhale1** [MachineMuse/MachineMusePowersuits#899]
I have a modded dedicated server and some friends and I are experiencing phantom fall damage and I think this mod is responsible. Basically, on the server we occasionally get half a heart of fall damage when running and sprinting on flat surfaces, and commonly when falling two blocks. Some people have gotten fall damage jumping off beds or just in the air.

It happens on single player as well, but less frequently. Removing this mod seems to stop the issue.

We are running Alpha 31 and Forge 14.23.5.2808, as well as many other mods so there very well could be a conflict.

There is no crash log and no relevant info in client logs, but I'll check server logs in a few hours and post them here as I believe they mention Modular Powersuits (I just don't have access atm).

**Comment by lehjr** [comment]
There are at least 2 possible causes for this... one is here (likely some obsolete code) : 
https://github.com/MachineMuse/MachineMusePowersuits/blob/1.12.2-experimental/src/main/java/net/machinemuse/powersuits/event/PlayerUpdateHandler.java#L78

The other is a vanilla issue:
https://bugs.mojang.com/browse/MCPE-26999

The first one is probably the likely cause, but I will need to do some more testing to confirm.

**Comment by lehjr** [comment]
Pretty sure this issue is fixed. If not let me know.

**Comment by AtomicWaffle14** [comment]
I'm having this issue with version 1.12.2-1.0.41, so I don't think it's fixed.

**Comment by lehjr** [comment]
@AtomicWaffle14 the code is there, you're welcome to fix it if you find the problem
